### PR TITLE
Migrate to v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
Hi, I've tried to migrate using v0.14 API.
Could you consider to start using v0.14 API in this plugin?

Please refer to [the upgrading v0.12 to v0.14 guide](http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12) in more details.

**Notice:** This PR contains breaking changes.

### CODE REVIEW

**Comment by takus** [comment]
Thanks for your contribution.
I'm going to read the document you provide and start to migrate soon.

**Comment by cosmo0920** [comment]
> I'm going to read the document you provide and start to migrate soon.

Thanks! I'm looking forward this. :sunglasses:

**Comment by takus** [comment]
Sorry for the late response again 🙇 

I read the upgrade guide and I think your PR looks good to merge. But I concern how many fluentd users use v0.14.x actually. Do you happen to know about that?

I know Fluentd core team strongly recommends to use v0.14 API. But, according to the guide, plugins which uses v0.14.x API don’t work on Fluentd v0.12.x. That means v0.12.x fluentd users need to do additional tasks to upgrade this plugin (e.g. use `gem specific_install...`).

**Comment by cosmo0920** [comment]
> I read the upgrade guide and I think your PR looks good to merge. But I concern how many fluentd users use v0.14.x actually. Do you happen to know about that?

td-agent3 will ship with Fluentd v0.14.x until 2017 Q1.
And users who want to use nano second precision time start to use Fluentd v0.14.

**Comment by Horgix** [comment]
Is it possible to get this merged ?

People that want to stay on v0.12.x just have to stay with the current gem version and it will stay fine, and people that are upgrading to v0.14.x or starting fresh with fluentd will be able to use this awesome plugin. This is already what's being done by some other plugin (i.e. https://github.com/reevoo/fluent-plugin-systemd , take a look at the "Support" section in the README)

**Comment by Horgix** [comment]
From @cosmo0920 :
> @Horgix, your production or staging environment already uses Fluentd v0.14?

We're already using fluentd v0.14 (td-agent v3 actually) in production, yes.

> We want to migrate v0.14 from v0.12 as soon as possible.

However we didn't have to handle the upgrade since we started using fluentd directly in v0.14.

>  But some plugin authors shall manage old Fluentd environment such as v0.12 and perhaps v0.10.

Well, upgrading to the v0.14 API will not break anything for existing users using the version `0.0.15` of the gem `fluent-plugin-ec2-metadata`

> Fluentd had not been included breaking changes for a long time, but now, migrating to use v0.14 API is breaking changes for Fluentd plugin developers and for staying to use old Fluentd users.

As a reminder, [the fluentd documentation is stating this](http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12):
> Fluentd core team strongly recommend to use v0.14 API to make your plugins stable, consistent and easy to test.

**Comment by Horgix** [comment]
For what it's worth, I tested this PR (don't worry, not in production) by :

- installing current gem : `td-agent-gem install fluent-plugin-ec2-metadata -v 0.0.15`
- Applying this PR by patching directly to `/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-ec2-metadata-0.0.15/lib/fluent/plugin/filter_ec2_metadata.rb` and `/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-ec2-metadata-0.0.15/lib/fluent/plugin/out_ec2_metadata.rb`

And everything is working fine; I tested both the `out` (match block) and `filter` (filter block).

So if this PR never gets merged I guess I'll fork it and create my own gem just so we can install it transparently without having to dirty-patch it.

@takus : your call :) I really like this plugin and sincerely wish I could use it in fluentd v`0.14.x`

**Comment by cosmo0920** [comment]
> So if this PR never gets merged I guess I'll fork it and create my own gem just so we can install it transparently without having to dirty-patch it.

Sadly, Fluentd community encourages to report issue and send PR into upstream.
So, we can just send ping, ping, and ping into original author to get merged this PR for now. :<

**Comment by Horgix** [comment]
From @cosmo0920 :
> Sadly, Fluentd community encourages to report issue and send PR into upstream.

Well, that's not sad, that's cool! I definitely prefer to go this way and I will help however I can to get this merged :)

>  So, we can just send ping, ping, and ping into original author to get merged this PR for now. :<

That's what I intend to do. But if in some weeks we have no news at all, I'll find a solution by myself

**Comment by takus** [comment]
Sorry for the late response. I'm very busy these days 😓  

@cosmo0920 
Thanks for your continuous contribution for this project. Could you maintain this project if you are okay? I added you as a contributor for this project. You can manage PRs by yourself. Please mention me when you need to publish new version into rubygem. Thanks in advance 🙇

**Comment by cosmo0920** [comment]
@takus Thank you for adding me to collaborator.
 
>  Could you maintain this project if you are okay?

OK. I'll continue to maintain this project.

 >  Please mention me when you need to publish new version into rubygem.

At first, I want to merge this PR soon. How long does it take to publish rubygems?
Thanks,

**Comment by takus** [comment]
Thanks!!

Published v0.0.16.
https://rubygems.org/gems/fluent-plugin-ec2-metadata/versions/0.0.16

**Comment by cosmo0920** [comment]
Great, thank you!

**Comment by Horgix** [comment]
@takus : no problem for the late response, it's fine, you're already way generous enough to contribute such a plugin to the community 🙂 

Congrats @cosmo0920 for being an official collaborator now!
If you need someone to test things, feel free to ping me.

Thanks for the merge and the new gem publishing 🎉

**Pull request merged**
